CREATE DATABASE COLLEGE;

USE COLLEGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);
SELECT*FROM STUDENT;
INSERT INTO STUDENT
(ID,NAME)
VALUES
(123,"AMAN");

CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEE_INFO(
ID INT PRIMARY KEY ,
NAME VARCHAR(50),
SALARY INT);
INSERT INTO EMPLOYEE_INFO
(ID,NAME,SALARY)
VALUES
(1,"ADAM",25000),
(2,"BOB",30000),
(3,"CASEY",40000);

CREATE TABLE TEMP1(
  ID INT PRIMARY KEY
);
INSERT INTO TEMP1 VALUES(101);

CREATE TABLE EMP(
ID INT PRIMARY KEY,
CITY VARCHAR(50),
 AGE INT,
 constraint AGE_CHECK CHECK (AGE>=18 AND CITY="DELHI")
);
CREATE DATABASE DEPARTMENT;
USE DEPARTMENT;
CREATE TABLE DEPAR_TABLE(
ROLL INT PRIMARY KEY,
NAME  VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);
 INSERT INTO DEPAR_TABLE(ROLL,NAME ,MARKS,GRADE,CITY)
 VALUES
 (101,"ANIL",78,'C',"PUNE"),
 (102,"BHUMIKA",93,'A',"MUMBAI"),
 (103,"CHETAN",85,'B',"MUMBAI"),
 (104,"DHURV",96,'A',"DELHI"),
 (105,"EMUANUEL",87,'F',"DELHI"),
 (106,"FARAH",80,'A',"PUNE");
 
 

SELECT distinct  GRADE FROM DEPAR_TABLE;
SELECT *FROM
DEPAR_TABLE WHERE 
MARKS BETWEEN 80 AND 90;
SELECT *FROM DEPAR_TABLE WHERE 
CITY IN("DELHI","MUMBAI");
SELECT * FROM DEPAR_TABLE WHERE 
CITY IN("AMRAVATI","NAGPUR");
SELECT *FROM DEPAR_TABLE WHERE 
CITY NOT IN ("DELHI","MUMBAI");
SELECT *FROM DEPAR_TABLE WHERE MARKS>75 LIMIT 4;
SELECT *FROM DEPAR_TABLE ORDER BY  MARKS ASC;
SELECT *FROM DEPAR_TABLE ORDER BY MARKS DESC 
LIMIT 3;
SELECT COUNT(MARKS) FROM DEPAR_TABLE;

SELECT CITY,NAME, MIN(MARKS)
FROM DEPAR_TABLE 
GROUP BY CITY,NAME;

SELECT GRADE ,COUNT(ROLL)
FROM DEPAR_TABLE
GROUP BY GRADE
ORDER BY GRADE ASC;

SELECT CITY
FROM DEPAR_TABLE
WHERE GRADE ='A'
GROUP BY CITY
HAVING MAX(MARKS)>90
ORDER BY  CITY DESC;

SET SQL_SAFE_UPDATES=0;
UPDATE DEPAR_TABLE
SET GRADE="B"
WHERE MARKS BETWEEN 80 AND 90;
	
UPDATE DEPAR_TABLE
SET MARKS = MARKS+1;
SELECT*FROM DEPAR_TABLE;
UPDATE DEPAR_TABLE
SET MARKS = 1;

UPDATE DEPAR_TABLE
SET MARKS = 13
WHERE MARKS<33;
SELECT *FROM DEPAR_TABLE;

DELETE  FROM DEPAR_TABLE
WHERE MARKS = 87;
SELECT*FROM DEPAR_TABLE;

CREATE DATABASE SHOP_INFO;
USE SHOP_INFO;
CREATE TABLE SHOP(
id INT primary key,
name VARCHAR(50)
);

CREATE TABLE teacher(
id INT primary key,
name varchar(50),
dep_id INT,
FOREIGN KEY (dep_id) REFERENCES SHOP(id)
on update cascade 
on delete cascade
);

